import Layout from "@/components/Layout";
import "../styles/globals.css";

export const metadata = {
  title: "Phanox Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}><Layout>{children}</Layout></body>
    </html>
  );
}
